version: "3.7"
services:

  db:
    image: postgres:9.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=pivorak
      - POSTGRES_PASSWORD=

  app:
    image: pivorak-web-app/app
    command: ["rails", "server", "-b", "0.0.0.0", "-e", "development"]
    build: .
    restart: always
    ports: 
      - "3000:3000"
    # environment:
    #   - pivorak_DATABASE_HOST=db
    depends_on:
      - db

  visualizer:
    image: dockersamples/visualizer:stable
    ports: 
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]